apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    info

    # Input Plugins
    [INPUT]
        Name              tail
        Tag               application.*
        Path              /var/log/application/*.log
        DB                /var/log/flb_application.db
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        Rotate_Wait       1m
        Ignore_Older      3d

    [INPUT]
        Name              tail
        Tag               system.*
        Path              /var/log/system/*.log
        DB                /var/log/flb_system.db
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        Rotate_Wait       1m
        Ignore_Older      3d

    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        Rotate_Wait       1m
        Ignore_Older      3d

    [INPUT]
        Name              tail
        Tag               network.*
        Path              /var/log/network/*.log
        DB                /var/log/flb_network.db
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        Rotate_Wait       1m
        Ignore_Older      3d

    [INPUT]
        Name              systemd
        Tag               systemd.*
        DB                /var/log/flb_systemd.db
        Mem_Buf_Limit     50MB
        Refresh_Interval  10
        Ignore_Older      3d

    # Parser Plugins
    [PARSER]
        Name   docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep On

    [PARSER]
        Name        regex
        Format      regex
        Regex       ^(?<timestamp>[^\s]+) \[(?<log_level>[^\]]+)\] (?<message>.+)$
        Time_Key    timestamp
        Time_Format %Y-%m-%d %H:%M:%S

    # Filter Plugins
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

    [FILTER]
        Name                record_modifier
        Match               *
        Record              service_name fluent-bit

    # Output Plugins
    [OUTPUT]
        Name            es
        Match           *
        Host            demo-opesearchcluter
        Port            443
        TLS             On
        AWS_Auth        On
        AWS_Region      ap-southeast-1
        Retry_Limit     6
        Index           fluent-bit
        Type            flb_type
        Logstash_Format On
        Retry_Limit     False

    [OUTPUT]
        Name            s3
        Match           *
        region          ap-southeast-1
        bucket          mws-fluent-bit-logs
        s3_key_format   logs/%Y/%m/%d/%H/%{key}.%{count}.%{uuid}.%{time_slice}.%{file_extension}
        time_slice_format %Y%m%d%H
        time_slice_wait   10m
        utc
        buffer_chunk_limit 2M
        buffer_queue_limit 8
        flush_interval    10s
        retry_limit      False
        compress         gzip